### ISSUE TITLE
OFL1.1-ja URL

### ISSUE THREAD

**Issue by shujisado** [fontworks-fonts/Rampart#3]
全フォントにプルリク出すのも面倒なのでこちらに書いておきます。

OSG-JPが運営するオープンソースライセンスの日本語訳サイトはOSDNより移転しておりますので、各フォントのREADME.jaに記載されているOFL1.1へのリンクは https://licenses.opensource.jp/OFL-1.1/OFL-1.1.html であるほうが有難いです。

**Comment by kokiabe** [comment]
ご指摘ありがとうございます!
他のリポジトリ含め修正しました。
